### ISSUE TITLE
QUESTION: event transitionEnd is not being fired

### ISSUE THREAD

**Issue by FluffyDiscord** [WrathChaos/react-navigation-helpers#349]
Hi, I would like to add listener to the `transitionEnd` event, but it seems it's not being triggered if I subscribe using the `navigationRef`

```ts
import {navigationRef} from "react-navigation-helpers";

const Comp = () => {
  useEffect(() => {
    const sub = navigationRef.addListener("transitionEnd", () => {
        // not called
    })

    return sub
  }, [])
}
```

```ts
const Comp = () => {
  const navigation = useNavigation()
  useEffect(() => {
    const sub = navigation.addListener("transitionEnd", () => {
        // works
    })

    return sub
  }, [])
}
```

Is that intended or is it a bug ?

**Comment by WrathChaos** [comment]
Hello @FluffyDiscord 
This is a bug, never use this listener :) 

I will take a look at it, if you have time PR's are always welcome :)

**Comment by FluffyDiscord** [comment]
> Hello @FluffyDiscord This is a bug, never use this listener :)
> 
> I will take a look at it, if you have time PR's are always welcome :)

I have been digging a bit and it seems that it's impossible to do it using the `createNavigationContainerRef` as it does not provide navigation-specific callbacks like `transitionEnd` and they need to be binded externally like:

![image](https://user-images.githubusercontent.com/10332247/185175501-beddf0a0-ff3c-43f9-8ca9-70e486efaa09.png)

This library would need to manager listeners by itself. Maybe something like this would do ?
```ts
// NavigationService.ts

const listeners: Record<string, ((...args: any[]) => void)[]> = {}

const removeListener = (
    event: string,
    callback: (...args: any[]) => void
) => {
  if (listeners[event]) {
    listeners[event] = listeners[event].filter((cb) => cb !== callback);
  }
}

export const addListener = (event: string, callback: any): () => void => {
  listeners[event] = listeners[event] || [];
  listeners[event].push(callback);

  return () => removeListener(event, callback);
}

const executeListeners = (eventName: string, ...args: any) => {
  if(listeners[eventName]) {
    listeners[eventName].forEach(fn => fn(args))
  }
}

export const listenerProps = {
  onTransitionEnd: (props, closing) => executeListeners("transitionEnd", props, closing)
}
```

```ts
import {navigationRef, listenerProps} from "react-navigation-helpers";

const Comp = () => {
  return (
    <NavigationContainer
        ref={navigationRef}
        onReady={() => {
            isReadyRef.current = true
        }}
        theme={isDarkMode ? DarkTheme : LightTheme}
    >
        <Stack.Navigator {...listeners} screenOptions={{headerShown: false}}></Stack.Navigator>
    </NavigationContainer>
  )
}
```

If I am not mistaken and this solution seems fine to you, I can create PR

**Comment by WrathChaos** [comment]
Aha! Great way and idea actually. 
Have you tested this listener manager on library itself? I love to contribute and test with your PR :) @FluffyDiscord

**Comment by FluffyDiscord** [comment]
> Aha! Great way and idea actually. Have you tested this listener manager on library itself? I love to contribute and test with your PR :) @FluffyDiscord

I have tested my PR fork and it works pretty well. Please let me know if theres something that needs changing.

**Comment by WrathChaos** [comment]
I will look at this today @FluffyDiscord  :)

**Comment by FluffyDiscord** [comment]
marged in https://github.com/WrathChaos/react-navigation-helpers/pull/351

**Comment by WrathChaos** [comment]
[Version 2.2.0](https://github.com/WrathChaos/react-navigation-helpers/releases/tag/2.2.0)

Thank you so much for the contribution @FluffyDiscord

**Comment by WrathChaos** [comment]
@FluffyDiscord Please test with the new version :)
