### ISSUE TITLE
'current' is a read-only property

### ISSUE THREAD

**Issue by hardik2792** [WrathChaos/react-navigation-helpers#45]
```
React.useEffect((): any => {
    return () => (isReadyRef.current = false);
                                ^
  }, []);
```
Cannot assign to 'current' because it is a read-only property.

**Comment by WrathChaos** [comment]
Hello @hardik2792,
Finally I've released the Version 2.0

### [Version 2](https://github.com/WrathChaos/react-navigation-helpers/releases/tag/2.0.0)

Please check it out. I've fixed this issue as well.
