### ISSUE TITLE
How does react-navigation-helpers differ from useNavigation hook?

### ISSUE THREAD

**Issue by 10000multiplier** [WrathChaos/react-navigation-helpers#90]
For example:

```jsx
import { useNavigation } from '@react-navigation/native';

function MyBackButton() {
  const navigation = useNavigation();

return (
    <Button
      title="Back"
      onPress={() => {
        navigation.goBack();
      }}
    />
  );
}
```

This seems to serve the same functionality.

Please correct me if I'm wrong.

**Comment by WrathChaos** [comment]
Hello @10000multiplier,

You can use this only in functional components, with `react-navigation-helper` there is no restriction. You can use it on both functional and stateful components. You do not need to prop drilling or anything with this library.

**Comment by 10000multiplier** [comment]
Awesome thanks.
